pipeline {
    agent any

    environment {
        // Load Telegram secrets from Jenkins credentials manager
        TF_VAR_telegram_bot_token = credentials('TELEGRAM_TOKEN_SECRET')
        TF_VAR_telegram_chat_id   = credentials('TELEGRAM_CHAT_ID')
        
        // Local database password for the dev environment container
        TF_VAR_postgres_password  = 'dev_secure_password_2026'
    }

    stages {
        stage('Fetch Source Code') {
            steps {
                echo 'Pulling latest files from repository...'
                checkout scm
            }
        }

        stage('Terraform Init') {
            steps {
                dir('terraform') {
                    echo 'Initializing terraform and downloading providers...'
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('terraform') {
                    echo 'Checking infrastructure changes...'
                    sh 'terraform plan'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('terraform') {
                    echo 'Deploying infrastructure mesh to local docker...'
                    sh 'terraform apply --auto-approve'
                }
            }
        }
    }
}
